---
- name: Создание нового пользователя в операционной системе Linux
  hosts: localhost
  vars:
    newuser: petrov.dv
    user_password: "password3z"
    group: sudo
    curl: curl
  tasks:
    - name: Создание нового пользователя в операционной системе Linux
      user:      
        name: "{{newuser}}"
        password: "{{ user_password | password_hash('sha512') }}"
        groups: "{{group}}"
        append: yes 
        create_home: true
        shell: /bin/bash 
    
    - name: Добавить алиас в .bashrc
      lineinfile:
        path: /home/{{ newuser }}/.bashrc
        regexp: "^alias la="
        line: "alias la='ls -la --color=auto'"
        insertafter: EOF
        state: present
        create: yes
        backup: yes
      become_user: "{{ newuser }}"
    
    - name: Получить информацию о пользователе
      user:
        name: "{{ newuser }}"
      register: user_info
      #ignore_errors: yes
    
    - name: Отладка - показать информацию о пользователе
      debug:
        msg: "User info: {{ user_info }}"
